# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VisionDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VisionDemo
  pod 'PureLayout', '3.1.4'
  pod 'R_category'
  pod 'TZImagePickerController'

end
